### ISSUE TITLE
Notifications: Notifications should be Ordered Decendingly

### ISSUE THREAD

**Issue by bluzi** [cuckoos-nest/cuckoos-nest#5]
Currently the notifications are ordered randomly. They should be ordered by date notified, so the last notification will be at the top of the list.

**Comment by josephshawcroft** [comment]
I can look at this. @bluzi is there an easy way of spoofing notifications so I can check this?

**Comment by bluzi** [comment]
Yup, there is, but first you need to upload a post. Then, you can like your own post and generate notifications.

**Comment by josephshawcroft** [comment]
Thanks, I'll have a look shortly :)

**Comment by josephshawcroft** [comment]
Are you sure this is still an issue? In notifications.page 'notificationService.getAll()' is called and this appers to order the list in descending time order:

```
public getAll(): Observable<NotificationModel[]> {
        return this.af.database.list(`/notifications/${this.authService.currentUser.$key}`, {
            query: {
                orderByChild: 'createdAt',
            },
        })
        .map(notifications => notifications.reverse());
    }
```
As such it seems to work fine for me when I run the app- notifications have always been in descending order so far for me.

**Comment by bluzi** [comment]
Looks like you're right. Someone must have solved it and forgot to update the issue.
Sorry if you spent time debugging this, feel free to take another issue. :)
